### PR TITLE
Fixing compatibility issues with latest Julia version

### PR DESCRIPTION
**Pull request by vboussange**
Updated dependencies to make ConScape running on latest Julia version:
- LightGraphs.jl swapped for Graphs.jl (LightGraphs.jl now deprecated)
- ProgressLogging.jl swapped for ProgressMeter.jl (ProgresLogging deprecated)

### CODE REVIEW

**Comment by andreasnoack** [comment]
Where did you see that ProgressLogging has been deprecated? I don't see any such notes at https://github.com/JuliaLogging/ProgressLogging.jl

**Comment by andreasnoack** [comment]
Thanks for the clarification. ProgressLogging integrates with VS Code so the progress logging is much nicer when using VS Code so I think we should try to keep it. I'll suggest that you restrict this PR to the LightGraph change and then file an issue with the error you see when trying to load ArchGDAL. Then we can debug it in that issue. Hopefully, we can fix whatever needs to be fixed upstream. If the issue can't be resolved then we can switch to ProgrressMeter.

**Comment by andreasnoack** [comment]
It looks like something went wrong in the latest commits, see https://github.com/ConScape/ConScape.jl/pull/19/files

**Comment by vboussange** [comment]
Hey @andreasnoack, sorry I indeed messed up the commits. Now everything should be fine, with a simple swap from LightGraphs.jl to Graphs.jl. Note that I have also removed the `[compat]` section.

I tried to reproduce the previous issue I had with ProgressLogging but I could not - everything seems to work fine as is now.

**Comment by andreasnoack** [comment]
> Note that I have also removed the `[compat]` section in the Project.toml.

I don't think that is a good idea. All packages are supposed to have such a section to ensure/help that it doesn't break.

**Comment by vboussange** [comment]
Fair enough, but in that case you probably want to set up something like CompatHelper, as the version as is probably does not run for latest Julia version.

**Comment by andreasnoack** [comment]
> in that case you probably want to set up something like CompatHelper

Latest CompatHelper run is [six hours old](https://github.com/ConScape/ConScape.jl/actions/runs/10276359232)

> as the version as is probably does not run for latest Julia version.

Last month's release [passed tests on Julia 1.10](https://github.com/ConScape/ConScape.jl/actions/runs/9795993227/job/27049430581)

🙂

**Comment by andreasnoack** [comment]
Superseded by #20

**Pull request closed without merging**
